Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations <- read.csv2("E:/kamagyana/Computing/DARET/Assignments/Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations.csv", sep="", comment.char="#", stringsAsFactors=FALSE)
View(Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations)
library(readr)
Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations <- read_csv("E:/kamagyana/Computing/DARET/Assignments/Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations.csv")
View(Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations)
library(readxl)
Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations <- read_excel("E:/kamagyana/Computing/DARET/Assignments/Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations.xlsx")
View(Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations)
head(ns)
biceps <- Example_WearableComputing_weight_lifting_exercises_biceps_curl_variations
heaD(biceps)
head(biceps)
str(biceps)
install.packages(c("foreign", "nnet"))
library(foreign)
library(nnet)
library(ggplot2)
library(reshape2)
install.packages("caret")
library(caret)
colnames(biceps)
bicepsdata <- biceps[,-c(1:6,11:36,49:57,68:82,86:111,124:149)]
colnames(bicepsdata)
logref <- relevel(bicepsdata$classe,ref = "A")
library(nnet)
bicepfit <- multinom(classe~.,data = bicepsdata)
summary(bicepfit)
z <- summary(bicepfit)$coefficients/summary(bicepfit)$standard.errors
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p
w <- (summary(bicepfit)$coefficients)^2/(summary(bicepfit)$standard.errors)^2
library(MASS)
stepbicep <- stepAIC(bicepfit,method="backward")
summary(stepbicep)
sum(is.na(bicepsdata))
library(MICE)
tempData <- mice(bicepsdata,m=5,maxit=50,meth='pmm',seed=500)
install.packages("mice")
library(mice)
tempData <- mice(bicepsdata,m=5,maxit=50,meth='pmm',seed=500)
compbicepsdata <- complete(tempData,1)
sum(is.na(compbicepsdata))
colnames(compbicepsdata)
bicepfitcomp <- multinom(classe~.,data = compbicepsdata)
zc <- summary(bicepfitcomp)$coefficients/summary(bicepfit)$standard.errors;pc <- (1 - pnorm(abs(zc), 0, 1)) * 2
wc <- (summary(bicepfitcomp)$coefficients)^2/(summary(bicepfitcomp)$standard.errors)^2
stepbicepcomp <- stepAIC(bicepfitcomp,method="backward")
summary(stepbicepcomp)
zcs <- summary(stepbicepcomp)$coefficients/summary(stepbicepcomp)$standard.errors;pcs <- (1 - pnorm(abs(zcs), 0, 1)) * 2
wcs <- (summary(stepbicepcomp)$coefficients)^2/(summary(stepbicepcomp)$standard.errors)^2
anova(bicepfit,test='Chisq')
plot(stepbicepcomp$fitted.values)
predbicep <- predict(stepbicepcomp, newdata = compbicepsdata, type = 'link')
predbicep <- predict(stepbicepcomp, newdata = compbicepsdata, type = 'probs')
predclass <- predict(stepbicepcomp, newdata = compbicepsdata, type = 'response')
predclass <- predict(stepbicepcomp, newdata = compbicepsdata, type = 'class')
vif(stepbicepcomp)
library(car)
vif(stepbicepcomp)
library(pROC)
install.packages("pROC")
library(pROC)
curve <- roc(classe ~ predclass, data = compbicepsdata)
curve <- multiclass.roc(classe ~ preclass, data = compbicepsdata)
curve <- multiclass.roc(classe ~ predclass, data = compbicepsdata)
head(compbicepsdata$predclass)
colnames(compbicepsdata)
head(predbicep)
curve <- multiclass.roc(classe ~ predbicep, data = compbicepsdata)
predbicep <- predict(stepbicepcomp, compbicepsdata,type='probs')
colnames(compbicepsdata)
nrow(compbicepsdata)
nrow(predbicep)
predclass
curve <- multiclass.roc(classe ~ predclass, data = compbicepsdata)
curve <- multiclass.roc(compbicepsdata$classe ~ predclass)
table(compbicepsdata$classe)
table(predclass)
original <- table(compbicepsdata$classe)
predicted <- table(predclass)
total <-rbind(original, predicted)
total <- t(total)
